"""initial migration

Revision ID: 92d7a895789f
Revises: 
Create Date: 2026-08-16 23:09:56.678934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import database


# revision identifiers, used by Alembic.
revision: str = '92d7a895789f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'CANCELLED', 'ERROR', name='jobstatus'), nullable=False),
    sa.Column('job_dir_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_input_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queued_dt', sa.DateTime(), nullable=False),
    sa.Column('started_dt', sa.DateTime(), nullable=True),
    sa.Column('finished_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('geometrystep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('atoms', database.models.AtomListJSON(), nullable=True),
    sa.Column('recorded_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geometry_step_job_id_recorded_dt', 'geometrystep', ['job_id', 'recorded_dt'], unique=False)
    op.create_table('jobmetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('TOTAL_SCF_ENERGY', 'ENERGY_CHANGE', 'MAX_GRAD', 'RMS_GRAD', 'MAX_STEP', 'RMS_STEP', name='metrictype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('recorded_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobmetric_job_id'), 'jobmetric', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobmetric_metric_type'), 'jobmetric', ['metric_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobmetric_metric_type'), table_name='jobmetric')
    op.drop_index(op.f('ix_jobmetric_job_id'), table_name='jobmetric')
    op.drop_table('jobmetric')
    op.drop_index('ix_geometry_step_job_id_recorded_dt', table_name='geometrystep')
    op.drop_table('geometrystep')
    op.drop_table('job')
    # ### end Alembic commands ###
